# Generated by Django 3.2.4 on 2021-07-02 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shoppings', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('status', models.CharField(choices=[('RE', 'requested'), ('AP', 'approved'), ('DE', 'denied'), ('CA', 'canceled')], default='RE', max_length=2)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.appuser')),
                ('shopping', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='shoppings.shopping')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('brand', models.CharField(max_length=30, null=True)),
                ('quantity', models.CharField(max_length=30)),
                ('price', models.FloatField()),
                ('shopping_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shoppings_requests.shoppingrequest')),
            ],
        ),
    ]
