# Generated by Django 3.2.4 on 2021-07-02 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shopping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PR', 'proposed'), ('AC', 'active'), ('CO', 'completed')], default='PR', max_length=2)),
                ('total_amount', models.FloatField()),
                ('venues', models.CharField(max_length=30)),
                ('datetime', models.DateTimeField()),
                ('shopper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.appuser')),
            ],
        ),
    ]
